### ISSUE TITLE
Updating YAML configuration for Pytorch to enable multiprocessing dataloaders

### ISSUE THREAD

**Issue by surajpaib** [MaastrichtU-IDS/dsri-documentation#10]
**Usecase:**
Dataloading on multiple processes can be really crucial when we dynamically load data from the filesystem.

**Current Scenario:**
Running a multiprocessed dataloader throws this error:
``` 
Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm). 
```

**Current Workaround:**
Refering to this, I've added the following sections in the current YAML configuration: 
https://docs.openshift.com/container-platform/3.7/dev_guide/shared_memory.html

Specifically I add the following under 

```
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
```
and

```
      volumes:
        - emptyDir:
            medium: Memory
          name: dshm
```

**Proposal:**
Maybe this could be added in the default config since multiprocessing is a very expected feature for pytorch deployments.
Ofcourse, given that there are no downsides to doing this by default.

**Comment by Binosha** [comment]
Hi @surajpaib ,

```
volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
```
VolumeMounts describe about the volume of inside the container. 

```
volumes:
        - emptyDir:
            medium: Memory
          name: dshm
```

Volumes describe about the outside of storage.
So according to the https://docs.openshift.com/container-platform/3.7/dev_guide/shared_memory.html also its explain Volumes should describe under the **SPEC** level and VolumeMounts should describe under the **SPEC-> CONTAINERS** level.

```
spec:
  volumes:                          
    - name: dshm
      emptyDir:
        medium: Memory
  containers:
    - image: kubernetes/pause
      name: hello-container1
      ports:
        - containerPort: 8080
          hostPort: 6061
      volumeMounts:                 
        - mountPath: /dev/shm
          name: dshm
```
